### ISSUE TITLE
alfred-workflows-renamer - problems with / in workflow name

### ISSUE THREAD

**Issue by iandol** [vitorgalvao/tiny-alfred-scripts#1]
This is a minor issue, but `alfred-workflows-renamer` cannot rename workflows that use a forward-slash in the name, e.g. "Presentation Mode ON/OFF". I assume other characters that interfere with path enumeration may also cause issues. Thanks for a helpful script by the way!

**Comment by vitorgalvao** [comment]
Nice catch. Fixed by stripping those characters (already updated the Homebrew formula). Thank you.
